---
# tasks file

    - name: Install dependencies
      apt: 
        name: ['python', 'python-setuptools', 'python-dev', 'build-essential', 'python-pip', 'python-mysqldb', 'python-apt']  
        state: present
      become: yes  
   
    - name: Install MySQL database
      apt: 
        name: ['mysql-server', 'mysql-client', 'libmysqlclient-dev'] 
        state: present
      become: yes  
      
    - name: Start MySQL Service
      service:
        name: mysql
        state: started
        enabled: yes
      become: yes  

    - name: Create Application Database
      mysql_db: 
        name: django_db 
        state: present
      become: yes  

    - name: Create A Database User
      mysql_user: 
        name: db_user
        password: Passw0rd
        priv: '*.*:ALL'
        state: present  
        host: '%'
      become: yes
